---

- hosts: all
  become: true
  remote_user: mirror

  handlers:
    - import_tasks: handlers.yaml

  tasks:
    - name: "Load OS specific vault"
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_hostname|lower }}.yml"
            - default.yml
          paths:
            - 'vault'

    - name: Enable EPEL
      dnf:
        name: epel-release
        state: latest

    - name: Install required software
      package:
        state: present
        name:
          - certbot
          - dstat
          - duperemove
          - lldpd
          - mosquitto
          - net-tools
          - '@nginx:1.20/common'
          - python3-certbot-nginx
          - python3-policycoreutils
          - policycoreutils-python-utils
          - rsync
          - rsync-daemon
          - screen
          - smartmontools
          - tcpdump
          - traceroute
          - vim
          - whois
          - byobu
          - cockpit
          - cockpit-ws
          - gnutls
          - rsyslog-gnutls

    - name: Update all software
      dnf:
        state: latest
        name: "*"

    - name: Set timezone
      timezone:
        name: America/Los_Angeles

    - name: Install KWF SSH keys
      authorized_key:
        user: mirror
        state: present
        key: https://github.com/phirephly.keys

    - name: Install Johns SSH keys
      authorized_key:
        user: mirror
        state: present
        key: https://github.com/warthog9.keys

    - name: Configure Nginx
      template:
        src: templates/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx

    - name: Install Nginx index template
      template:
        src: templates/autoindex.xslt
        dest: /usr/share/nginx/html/autoindex.xslt
      notify:
        - reload nginx

    - name: Install HTTP Favicon
      copy:
        src: files/favicon.ico
        dest: /usr/share/nginx/html/favicon.ico

    - name: Install HTTP Robots.txt
      copy:
        src: files/robots.txt
        dest: /usr/share/nginx/html/robots.txt

    - name: Configure nftables firewall
      template:
        src: templates/nftables.conf
        dest: /etc/sysconfig/nftables.conf
      notify: reload firewall

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Enable nftables
      service:
        name: nftables
        state: started
        enabled: yes

    - name: Copy over sysctl IP stack optimizations
      copy:
        src: files/sysctl.performancetune.conf
        dest: /etc/sysctl.d/50-performancetune.conf
      notify: reload sysctl

    - name: Install Update Script
      template:
        src: templates/update-mirror.sh
        dest: /usr/local/bin/update-mirror.sh
        mode: '0755'

    - name: Schedule update script and duperemove
      copy:
        src: files/cron.d/updatemirror
        dest: /etc/cron.d/updatemirror

    - name: Create Mirror Data Dir
      file:
        path: /data/mirror
        state: directory
        owner: mirror
        group: mirror

    - name: Create Mirror Log Dir
      file:
        path: /var/log/mirror
        state: directory
        owner: mirror
        group: mirror

    - name: Create Mirror Lock Dir
      file:
        path: /home/mirror/lock
        state: directory
        owner: mirror
        group: mirror

    - name: Configure Rsyncd
      template:
        src: templates/rsyncd.conf
        dest: /etc/rsyncd.conf

    - name: Enable rsyncd
      service:
        name: rsyncd
        state: started
        enabled: yes

    - name: Install mqtt-exec
      copy:
        src: files/mqtt-exec
        dest: /usr/local/bin/mqtt-exec
        mode: '0755'

    - name: Install mqtt-exec service unit
      copy:
        src: files/systemd.mqtt-exec.service
        dest: /etc/systemd/system/mqtt-exec.service

    - name: Enable mqtt-exec service
      systemd:
        name: mqtt-exec.service
        state: started
        enabled: yes

    - name: Enable LLDP
      service:
        name: lldpd
        state: started
        enabled: yes

