---

hostedprojects:
  - almalinux
  - archlinux
  - epel-amd64
  - fedora-amd64
  - gimp
  - kali-images
  - manjaro
  - opensuse
  - rpmfusion-nonfree
  - tdf
  - ubuntu
  - ubuntu-releases
  - videolan

tls_setup: True
site_sponsor: "EdgeUno"
site_sponsor_url: "https://edgeuno.com/"

geolocation:
  continent: South America
  country: CO
  state_province: Bogota
  city: Bogota

