---

hostedprojects:
  - archlinux
  - epel
  - centos
  - fedora-amd64
  - kdeftp-stable
  - manjaro
  - ubuntu-releases

tls_setup: True
site_sponsor: "Minnesota VoIP"
site_sponsor_url: "https://www.mnvoip.com/"

