---

hostedprojects:
  - almalinux
  - centos
  - epel
  - fedora-amd64
  - kdeftp-stable
  - opensuse
  - ubuntu-releases

tls_setup: True
site_sponsor: "NNENIX"
site_sponsor_url: "https://www.nnenix.net/"

