---

hostedprojects:
  - almalinux
  - archlinux
  - centos
  - epel
  - fdroid-repo
  - fedora-amd64
  - gimp
  - manjaro
  - ubuntu-releases
  - videolan

tls_setup: True
site_sponsor: "OpenColo"
site_sponsor_url: "https://opencolo.com/"

