---

hostedprojects:
  - almalinux
  - archlinux
  - epel-amd64
  - fedora-amd64
  - gimp
  - manjaro
  - ubuntu-releases
  - videolan

tls_setup: True
site_sponsor: "YYCIX"
site_sponsor_url: "https://yycix.ca/"

geolocation:
  continent: North America
  country: CA
  state_province: Alberta
  city: Calgary

